#!/usr/bin/env python3
"""Create TIFF figures and editable PPTX for JE submission.

JE requires:
- Figures submitted as separate files (TIFF or high-res PNG)
- This script also generates editable PPTX (1 slide per figure with caption)
"""

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from PIL import Image
import os
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
JE_DIR = os.path.join(OUTPUT_DIR, 'je')
os.makedirs(JE_DIR, exist_ok=True)

# Source figures (already generated by analysis pipeline)
figure_sources = [
    {
        'num': 1,
        'png': os.path.join(OUTPUT_DIR, 'fig1_neuropathic_unadjusted_en.png'),
        'tiff_fallback': os.path.join(OUTPUT_DIR, 'Fig1_neuropathic_unadjusted.tiff'),
        'caption': (
            'Figure 1. Outpatient neuropathic pain drug prescribing per surgery by '
            'prefecture. Bars represent individual prefectures ordered by prescribing '
            'index. Bars indicate regional blocks (distinguished by colour and hatch pattern). '
            'Dashed line indicates the national mean.'
        ),
    },
    {
        'num': 2,
        'png': os.path.join(OUTPUT_DIR, 'fig2_confounder_correlations_en.png'),
        'tiff_fallback': os.path.join(OUTPUT_DIR, 'Fig2_confounder_correlations.tiff'),
        'caption': (
            'Figure 2. Correlation between neuropathic pain prescribing and confounder '
            'disease proxies across 47 prefectures. Each marker represents a regional block (distinguished by colour and shape). '
            'Diabetes drugs show the strongest correlation (r=0.87).'
        ),
    },
    {
        'num': 3,
        'png': os.path.join(OUTPUT_DIR, 'fig4_region_unadj_vs_adj_en.png'),
        'tiff_fallback': os.path.join(OUTPUT_DIR, 'Fig4_region_unadj_vs_adj.tiff'),
        'caption': (
            'Figure 3. Regional comparison of neuropathic pain prescribing: '
            '(a) unadjusted and (b) after adjustment for confounding disease proxies. '
            'Error bars indicate SD.'
        ),
    },
    {
        'num': 4,
        'png': os.path.join(OUTPUT_DIR, 'fig_cslc_demand_supply_en.png'),
        'tiff_fallback': None,
        'caption': (
            'Figure 4. Demand\u2013supply dissociation: CSLC symptom prevalence rate '
            '(per 1,000 population) vs acute analgesic prescribing per surgery '
            'across 47 prefectures. Each marker represents a regional block (distinguished by colour and shape). '
            'The near-zero correlation (r=0.03, P=0.85) indicates that '
            'prescribing variation is dissociated from symptom burden.'
        ),
    },
]

# ============================================================
# Generate TIFFs (300 DPI, LZW compression)
# ============================================================
print('--- Generating TIFF figures ---')
for fig in figure_sources:
    num = fig['num']
    src = fig['png']
    if not os.path.exists(src):
        if fig['tiff_fallback'] and os.path.exists(fig['tiff_fallback']):
            src = fig['tiff_fallback']
        else:
            print(f'  WARNING: No source found for Figure {num}')
            continue

    tiff_out = os.path.join(JE_DIR, f'JE_figure{num}.tiff')
    img = Image.open(src)
    if img.mode == 'RGBA':
        bg = Image.new('RGB', img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[3])
        img = bg
    elif img.mode != 'RGB':
        img = img.convert('RGB')
    img.save(tiff_out, 'TIFF', dpi=(300, 300), compression='tiff_lzw')
    print(f'  Figure {num}: {tiff_out} ({os.path.getsize(tiff_out) / 1024:.0f} KB)')

# ============================================================
# Generate PPTX (editable figures, 1 slide per figure)
# ============================================================
print('\n--- Generating PPTX ---')
prs = Presentation()
prs.slide_width = Inches(13.333)
prs.slide_height = Inches(7.5)

for fig in figure_sources:
    num = fig['num']
    src = fig['png']
    if not os.path.exists(src):
        if fig['tiff_fallback'] and os.path.exists(fig['tiff_fallback']):
            src = fig['tiff_fallback']
        else:
            continue

    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank

    # Title
    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(12), Inches(0.5))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = f'Figure {num}'
    p.font.size = Pt(24)
    p.font.bold = True
    p.font.name = 'Arial'

    # Figure image
    img_path = src
    img = Image.open(img_path)
    w, h = img.size
    max_w = Inches(11)
    max_h = Inches(5.5)
    aspect = w / h
    if aspect > (11 / 5.5):
        img_w = max_w
        img_h = int(max_w / aspect)
    else:
        img_h = max_h
        img_w = int(max_h * aspect)

    left = (prs.slide_width - img_w) // 2
    slide.shapes.add_picture(img_path, left, Inches(0.8), img_w, img_h)

    # Caption
    cap_top = Inches(0.8) + img_h + Inches(0.1)
    capBox = slide.shapes.add_textbox(Inches(0.5), cap_top, Inches(12), Inches(1.0))
    tf2 = capBox.text_frame
    tf2.word_wrap = True
    p2 = tf2.paragraphs[0]
    p2.text = fig['caption']
    p2.font.size = Pt(12)
    p2.font.name = 'Arial'

pptx_out = os.path.join(JE_DIR, 'JE_figures_EN.pptx')
prs.save(pptx_out)
print(f'  Saved: {pptx_out}')
